//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_no_update.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool initializationOver {
            get {
                return ((bool)(this["initializationOver"]));
            }
            set {
                this["initializationOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string languagePath {
            get {
                return ((string)(this["languagePath"]));
            }
            set {
                this["languagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection alreadySetGames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["alreadySetGames"]));
            }
            set {
                this["alreadySetGames"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>ENGLISH language pack for Steam_no_update 1.00 //this line is free to use " +
            "other than putting \'language pack for Steam_no_update 1.00\' anywhere on this lin" +
            "e. But this will also be shown when language pack information is clicked on. Als" +
            "o, if there are any {} with numbers in them, keep them as is while translating, " +
            "otherwise they will create issues. Also double spaces are new Line/Enter so keep" +
            " them as is.</string>\r\n  <string> Force Continue?</string>\r\n  <string>Error</str" +
            "ing>\r\n  <string>Success</string>\r\n  <string>load a language pack(.txt)</string>\r" +
            "\n  <string>Successfully changed the language pack to {0}, if you save this, you " +
            "can always reset to default by writing -RESET as an argument while starting the " +
            "app</string>\r\n  <string>The file given does not contain {0} in the first line</s" +
            "tring>\r\n  <string>The file given has less lines than ({0}) this version ({1}) of" +
            " the app uses</string>\r\n  <string>Are You Sure? This will quit the app</string>\r" +
            "\n  <string>Sorry I scared you</string>\r\n  <string>Accept</string>\r\n  <string>Rej" +
            "ect</string>\r\n  <string>By clicking accept, you acknowledge that I am not respon" +
            "sible for any harm caused to your Steam files by my poor coding (lol).</string>\r" +
            "\n  <string>Failed to add find game from uninstallers: Name:{0},ID:{1},Depot:{2}," +
            "Path:{3}</string>\r\n  <string>A game add failed but not sure why lol im lazy:</st" +
            "ring>\r\n  <string>No (New if they have already been added) Steam game was found!<" +
            "/string>\r\n  <string>Select which game to stop updating, double click to edit its" +
            " properties</string>\r\n  <string>Select which Manifests to change</string>\r\n  <st" +
            "ring>The last time this game was stopped from being updated</string>\r\n  <string>" +
            "Link to the original Creator Website</string>\r\n  <string>Link to the modifier Gi" +
            "thub page</string>\r\n  <string>Link to the website used for the Icons</string>\r\n " +
            " <string>Apply The Depot ManifestID Change</string>\r\n  <string>Find the folder t" +
            "he game files are located in</string>\r\n  <string>Click to get the corresponding " +
            "manifest(s) to the depot id(s) from Steam</string>\r\n  <string>Click to get infor" +
            "mation regarding the app</string>\r\n  <string>Click to search for games automatic" +
            "ally</string>\r\n  <string>Click to save the added games to your local files--THIS" +
            " WILL CREATE FOLDERS AND A FILE-BE AWARE!</string>\r\n  <string>Add a new game</st" +
            "ring>\r\n  <string>Remove the selected game</string>\r\n  <string>{0} install Folder" +
            ":</string>\r\n  <string>Latest {0} Manifest ID(s)</string>\r\n  <string>Select All</" +
            "string>\r\n  <string>De/Select all choices</string>\r\n  <string>Choose the folder w" +
            "here the game is under the Steam\\steamapps\\common folder</string>\r\n  <string>It " +
            "seems like the Folder you selected is incorrect. You can go to the properties of" +
            " the game in Steam and click on \'Browse Game files\' for an easy method to get th" +
            "e correct path</string>\r\n  <string>Steam seems to be running, please exit it to " +
            "apply the patch</string>\r\n  <string>The Manifest ID you entered is incorrect. It" +
            " should be a long number with somwhere between 15 and 20 digits (i hope). Make s" +
            "ure to not accidently enter any spaces</string>\r\n  <string>Seems like this updat" +
            "e is already applied. I\'ll apply it again for good measure</string>\r\n  <string>T" +
            "here aren\'t the same number of Manifests to correspond with all of the Depots</s" +
            "tring>\r\n  <string>The manifests box has letters in it which is not right!</strin" +
            "g>\r\n  <string>Click again without selecting anything to cancel</string>\r\n  <stri" +
            "ng>Only turned off auto update</string>\r\n  <string>No change applied!</string>\r\n" +
            "  <string>Apply The Depot ManifestID Change</string>\r\n  <string>Patch applied. S" +
            "team might still claim that an update available, but it should not actually down" +
            "load anything.  In doubt, create a backup.  To actually update your game at a la" +
            "ter point, go to the properties of the game in Steam and verify the game integri" +
            "ty.    **Just simply installing an update at a later point without verifying the" +
            " game integrity will probably break your game**</string>\r\n  <string>This tool mo" +
            "difies a config file of Steam to make it think that you already have the last ve" +
            "rsion (Indicated by the correct Manifest ID) eventho you are not.  You will need" +
            " to redo this whenever an Update is released (Basically whenever Steam prompts y" +
            "ou to Update to start the game you use this tool instead to fake that you did up" +
            "date)</string>\r\n  <string>no Depot or App Id entered!</string>\r\n  <string>Loadin" +
            "g..</string>\r\n  <string>Automatically retreiving the Manifest ID failed. Copy th" +
            "e latest \'Manifest ID\' from the site. Make sure that \'Last update\' under the \'Cr" +
            "eation date\' looks correct, to confirm the site has already spotted the latest u" +
            "pdate! Open the website?</string>\r\n  <string>failed retrieving depot {0},</strin" +
            "g>\r\n  <string>Retrieve</string>\r\n  <string>{0} install Folder:</string>\r\n  <stri" +
            "ng>Latest {0} Manifest ID(s)</string>\r\n  <string>Change the name of the game? Pr" +
            "ess OK to save and edit appID</string>\r\n  <string>Edit Game Name</string>\r\n  <st" +
            "ring>Change the appID of the game? Press OK to save and edit depotID</string>\r\n " +
            " <string>Edit Game ID</string>\r\n  <string>Change the depotID of the game? Press " +
            "OK to save and edit Installation Path</string>\r\n  <string>Edit Game depotID</str" +
            "ing>\r\n  <string>You can only write numbers and \',\' to seperate them</string>\r\n  " +
            "<string>You can only write numbers for APPID</string>\r\n  <string>Choose which Ma" +
            "nifestIDs of Depots to Change</string>\r\n  <string>This will save the current sta" +
            "te and create a physical file in </string>\r\n  <string>  and will also continue s" +
            "aving untill you press again and cancel or delete the save file    Continue Anyw" +
            "ays?</string>\r\n  <string>This will stop autosaving into the file but will NOT de" +
            "lete the file in </string>\r\n  <string>, are you sure?</string>\r\n  <string>Would " +
            "you like to search for games automatically?</string>\r\n  <string>Update Never Can" +
            "celled</string>\r\n  <string>the following game failed to load:{0}  should it be d" +
            "eleted to prevent this same error in the future?</string>\r\n  <string>Apply</stri" +
            "ng>\r\n  <string>Choose &amp; Apply</string>\r\n  <string>Apply Selected</string>\r\n " +
            " <string>ALL Installed Depots</string>\r\n  <string>Disable Autoupdate</string>\r\n " +
            " <string>Selected Game</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultLanguagePack {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultLanguagePack"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>ENGLISH language pack for Steam_no_update 1.00 //this line is free to use " +
            "other than putting \'language pack for Steam_no_update 1.00\' anywhere on this lin" +
            "e. But this will also be shown when language pack information is clicked on. Als" +
            "o, if there are any {} with numbers in them, keep them as is while translating, " +
            "otherwise they will create issues. Also double spaces are new Line/Enter so keep" +
            " them as is.</string>\r\n  <string> Force Continue?</string>\r\n  <string>Error</str" +
            "ing>\r\n  <string>Success</string>\r\n  <string>load a language pack(.txt)</string>\r" +
            "\n  <string>Successfully changed the language pack to {0}, if you save this, you " +
            "can always reset to default by writing -RESET as an argument while starting the " +
            "app</string>\r\n  <string>The file given does not contain {0} in the first line</s" +
            "tring>\r\n  <string>The file given has less lines than ({0}) this version ({1}) of" +
            " the app uses</string>\r\n  <string>Are You Sure? This will quit the app</string>\r" +
            "\n  <string>Sorry I scared you</string>\r\n  <string>Accept</string>\r\n  <string>Rej" +
            "ect</string>\r\n  <string>By clicking accept, you acknowledge that I am not respon" +
            "sible for any harm caused to your Steam files by my poor coding (lol).</string>\r" +
            "\n  <string>Failed to add find game from uninstallers: Name:{0},ID:{1},Depot:{2}," +
            "Path:{3}</string>\r\n  <string>A game add failed but not sure why lol im lazy:</st" +
            "ring>\r\n  <string>No (New if they have already been added) Steam game was found!<" +
            "/string>\r\n  <string>Select which game to stop updating, double click to edit its" +
            " properties</string>\r\n  <string>Select which Manifests to change</string>\r\n  <st" +
            "ring>The last time this game was stopped from being updated</string>\r\n  <string>" +
            "Link to the original Creator Website</string>\r\n  <string>Link to the modifier Gi" +
            "thub page</string>\r\n  <string>Link to the website used for the Icons</string>\r\n " +
            " <string>Apply The Depot ManifestID Change</string>\r\n  <string>Find the folder t" +
            "he game files are located in</string>\r\n  <string>Click to get the corresponding " +
            "manifest(s) to the depot id(s) from Steam</string>\r\n  <string>Click to get infor" +
            "mation regarding the app</string>\r\n  <string>Click to search for games automatic" +
            "ally</string>\r\n  <string>Click to save the added games to your local files--THIS" +
            " WILL CREATE FOLDERS AND A FILE-BE AWARE!</string>\r\n  <string>Add a new game</st" +
            "ring>\r\n  <string>Remove the selected game</string>\r\n  <string>{0} install Folder" +
            ":</string>\r\n  <string>Latest {0} Manifest ID(s)</string>\r\n  <string>Select All</" +
            "string>\r\n  <string>De/Select all choices</string>\r\n  <string>Choose the folder w" +
            "here the game is under the Steam\\steamapps\\common folder</string>\r\n  <string>It " +
            "seems like the Folder you selected is incorrect. You can go to the properties of" +
            " the game in Steam and click on \'Browse Game files\' for an easy method to get th" +
            "e correct path</string>\r\n  <string>Steam seems to be running, please exit it to " +
            "apply the patch</string>\r\n  <string>The Manifest ID you entered is incorrect. It" +
            " should be a long number with somwhere between 15 and 20 digits (i hope). Make s" +
            "ure to not accidently enter any spaces</string>\r\n  <string>Seems like this updat" +
            "e is already applied. I\'ll apply it again for good measure</string>\r\n  <string>T" +
            "here aren\'t the same number of Manifests to correspond with all of the Depots</s" +
            "tring>\r\n  <string>The manifests box has letters in it which is not right!</strin" +
            "g>\r\n  <string>Click again without selecting anything to cancel</string>\r\n  <stri" +
            "ng>Only turned off auto update</string>\r\n  <string>No change applied!</string>\r\n" +
            "  <string>Apply The Depot ManifestID Change</string>\r\n  <string>Patch applied. S" +
            "team might still claim that an update available, but it should not actually down" +
            "load anything.  In doubt, create a backup.  To actually update your game at a la" +
            "ter point, go to the properties of the game in Steam and verify the game integri" +
            "ty.    **Just simply installing an update at a later point without verifying the" +
            " game integrity will probably break your game**</string>\r\n  <string>This tool mo" +
            "difies a config file of Steam to make it think that you already have the last ve" +
            "rsion (Indicated by the correct Manifest ID) eventho you are not.  You will need" +
            " to redo this whenever an Update is released (Basically whenever Steam prompts y" +
            "ou to Update to start the game you use this tool instead to fake that you did up" +
            "date)</string>\r\n  <string>no Depot or App Id entered!</string>\r\n  <string>Loadin" +
            "g..</string>\r\n  <string>Automatically retreiving the Manifest ID failed. Copy th" +
            "e latest \'Manifest ID\' from the site. Make sure that \'Last update\' under the \'Cr" +
            "eation date\' looks correct, to confirm the site has already spotted the latest u" +
            "pdate! Open the website?</string>\r\n  <string>failed retrieving depot {0},</strin" +
            "g>\r\n  <string>Retrieve</string>\r\n  <string>{0} install Folder:</string>\r\n  <stri" +
            "ng>Latest {0} Manifest ID(s)</string>\r\n  <string>Change the name of the game? Pr" +
            "ess OK to save and edit appID</string>\r\n  <string>Edit Game Name</string>\r\n  <st" +
            "ring>Change the appID of the game? Press OK to save and edit depotID</string>\r\n " +
            " <string>Edit Game ID</string>\r\n  <string>Change the depotID of the game? Press " +
            "OK to save and edit Installation Path</string>\r\n  <string>Edit Game depotID</str" +
            "ing>\r\n  <string>You can only write numbers and \',\' to seperate them</string>\r\n  " +
            "<string>You can only write numbers for APPID</string>\r\n  <string>Choose which Ma" +
            "nifestIDs of Depots to Change</string>\r\n  <string>This will save the current sta" +
            "te and create a physical file in </string>\r\n  <string>  and will also continue s" +
            "aving untill you press again and cancel or delete the save file    Continue Anyw" +
            "ays?</string>\r\n  <string>This will stop autosaving into the file but will NOT de" +
            "lete the file in </string>\r\n  <string>, are you sure?</string>\r\n  <string>Would " +
            "you like to search for games automatically?</string>\r\n  <string>Update Never Can" +
            "celled</string>\r\n  <string>the following game failed to load:{0}  should it be d" +
            "eleted to prevent this same error in the future?</string>\r\n  <string>Apply</stri" +
            "ng>\r\n  <string>Choose &amp; Apply</string>\r\n  <string>Apply Selected</string>\r\n " +
            " <string>ALL Installed Depots</string>\r\n  <string>Disable Autoupdate</string>\r\n " +
            " <string>Selected Game</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection languagePack {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["languagePack"]));
            }
            set {
                this["languagePack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SavingTurnedOn {
            get {
                return ((bool)(this["SavingTurnedOn"]));
            }
            set {
                this["SavingTurnedOn"] = value;
            }
        }
    }
}
